### ISSUE TITLE
Extension is broken

### ISSUE THREAD

**Issue by jvolker** [OpenframeProject/Openframe-Website#10]
As reported here the extension seems broken: https://github.com/OpenframeProject/Openframe/issues/40#issuecomment-522178825

This is the error message that comes up:
![image](https://user-images.githubusercontent.com/546852/63223952-8f612980-c1bd-11e9-9c3b-3ec1914659d2.png)

**Comment by jvolker** [comment]
Entering the two commands described [here](https://www.raspberrypi.org/forums/viewtopic.php?p=1159230&sid=5b2815d561980a49be67a9bfe79e33cb#p1159230
) solved the issue for me:

> I tried everything; I could think or find. When I ran `sudo usermod -a -G tty pi`, my message changed from tty0 access to virtual console 2.
>
> I found this on an Ubuntu forum; it worked for me `sudo apt-get install xserver-xorg-legacy`, so I assume that means it is an issue with the xserver upgrade.

Would it be a good idea to add this to the install script?

**Comment by jeremydouglass** [comment]
I encountered the same issue on a fresh install of openframe. I went through the https://openframe.io/stream examples, and none of the ~18 website examples worked. All produced the same error message, pictured above.

I'm assuming that, although this issue is closed, the fix isn't in the installed release yet?

Here is the log:

```
X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.15.0-48-generic armv8l Raspbian
Current Operating System: Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l
Kernel command line: coherent_pool=1M 8250.nr_uarts=0 bcm2708_fb.fbwidth=1080 bcm2708_fb.fbheight=1920 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=/dev/mmcblk0p7 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles
Build Date: 05 June 2019  12:49:54PM
xorg-server 2:1.20.4-1+rpt1 (https://www.debian.org/support) 
Current version of pixman: 0.36.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/home/pi/.local/share/xorg/Xorg.0.log", Time: Sat Sep 28 13:32:52 2019
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/home/pi/.local/share/xorg/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
xinit: giving up
xinit: unable to connect to X server: Connection refused
xinit: server error
```

**Comment by jeremydouglass** [comment]
Uninstalling and reinstalling with `openframe -u openframe-website; openframe -o openframe-website` did not change anything, but it started working as soon as I manually ran:

```
sudo apt-get install xserver-xorg-legacy
```

**Comment by jmwohl** [comment]
Thanks @jeremydouglass — just released the latest version which includes this dependency.
